project:
  type: website
  output-dir: docs

website:
  title: "Florentin Lecomte"
  favicon: photo_logo.jpg
  navbar:
    logo: photo_logo.jpg
    background: primary
    search: false
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/florentin-lecomte-97208b253/
      - icon: github
        href: https://github.com/FlorentinLecomte
      - text: "FR"
        href: index.qmd
      - text: "EN"
        href: index-en.qmd
  page-footer:
    left: "© 2026 Florentin Lecomte. Tous droits réservés."
    right:
      - icon: envelope
        text: lecomteflorentin@gmail.com
    background: light
  site-url: "https://florentinlecomte.github.io/website/"
  open-graph:
    title: "Florentin Lecomte | Mathématiques Appliquées & Modélisation"
    description: "Élève ingénieur spécialisé en modélisation pour la biologie et la médecine. Découvrez mon portfolio académique (actuellement en recherche d'un financement de thèse)."
    image: photo_logo.jpg

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left